idf_component_register(
    SRCS
        "main.c"
        "board.c"
        "capsule.c"
        "net.c"
        "http_api.c"
        "validate.c"
        "ui.c"
        "motion.c"
        "beep.c"
        "fonts/font_digits_128.c"
        "fonts/font_digits_72.c"
        "fonts/font_text_40.c"
        "fonts/font_small_22.c"
    INCLUDE_DIRS ".")
